[flows]

[flows.default]
allowed_calls = []

[flows.jira_summarizer]
allowed_calls = ["jira.*", "notion.*"]

[flows.graph_policy]
allowed_calls = [".*graph.*"]

[flows.github]
allowed_calls = [".*github.*"]